In [1]:
import pandas as pd
import numpy as np

In [2]:
v5 = pd.read_csv('/content/V5.csv')

In [3]:
df = v5.copy()

In [5]:
df2 = df.iloc[::2]
df2.iloc[0,3]

111440.0

In [6]:
df2.iloc[332,3]

256200.0

In [7]:
df3 = df.iloc[1::2]
df3.iloc[332,3]

352940.0

In [8]:
df4 = df.iloc[:, 1::2]
df4.iloc[100,5]

'West'

In [4]:
df1 = df.iloc[::2, ::2]
df1.iloc[255, 3]

'Detached House'

In [11]:
recent = df['Year'].max()
last_six = recent - 6
last_six

2016

In [13]:
df['Year'].loc[df.Year > last_six].count()

4749

In [14]:
df.loc[(df.num_rooms == 3) & (df.num_bathrooms == 3)].count()

Date                 2730
Year                 2730
Locality             2393
Estimated Value      2374
Sale Price           2730
Property             2730
Residential          2730
num_rooms            2730
num_bathrooms        2730
carpet_area          2386
property_tax_rate    2730
Face                 2730
dtype: int64

In [16]:
df.loc[(df.num_rooms == 3) | (df.num_bathrooms == 3)].count()

Date                 8591
Year                 8591
Locality             7528
Estimated Value      7528
Sale Price           8591
Property             8591
Residential          8591
num_rooms            8591
num_bathrooms        8591
carpet_area          7524
property_tax_rate    8591
Face                 8591
dtype: int64

In [18]:
condition = (df.num_rooms == 3) & (df.Locality == 'Greenwich') & (df.Year == 2022) & ((df.Face == 'North')| (df.Face == 'East'))

In [19]:
df.loc[condition].count()

Date                 42
Year                 42
Locality             42
Estimated Value      32
Sale Price           42
Property             42
Residential          42
num_rooms            42
num_bathrooms        42
carpet_area          37
property_tax_rate    42
Face                 42
dtype: int64

In [26]:
df['Date'] = pd.to_datetime(df['Date'])

In [27]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [28]:
df['Month'] = df['Date'].dt.month

In [29]:
df.head(20)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face,Month
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South,1
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South,1
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South,1
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East,1
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East,1
5,2009-01-02,2009,Greenwich,2868880.0,3300000.0,Single Family,Detached House,3,1,1039.0,1.025953,North,1
6,2009-01-02,2009,Norwalk,571060.0,1000000.0,Single Family,Detached House,3,2,NaN,1.025953,South,1
7,2009-01-02,2009,Greenwich,592760.0,920000.0,Single Family,Detached House,3,3,937.0,1.025953,North,1
8,2009-01-02,2009,NaN,603540.0,1680000.0,Single Family,Detached House,3,1,1039.0,1.025953,East,1
9,2009-01-02,2009,Bridgeport,137901.0,245000.0,Single Family,Detached House,3,1,956.0,1.025953,West,1
10,2009-01-03,2009,Bridgeport,122150.0,256500.0,Single Family,Detached House,3,1,926.0,1.025953,South,1
11,2009-01-03,2009,Norwalk,NaN,1340000.0,Single Family,Detached House,3,1,936.0,1.025953,North,1
12,2009-01-03,2009,Bridgeport,103950.0,310000.0,Single Family,Detached House,3,2,997.0,1.025953,East,1
13,2009-01-03,2009,Greenwich,1046920.0,600000.0,Single Family,Detached House,3,3,1068.0,1.025953,South,1
14,2009-01-04,2009,Bridgeport,NaN,300000.0,Three Family,Triplex,6,4,2174.0,1.025953,South,1
15,2009-01-04,2009,Norwalk,208880.0,370000.0,Single Family,Detached House,3,2,1063.0,1.025953,South,1
16,2009-01-05,2009,Waterbury,74620.0,206500.0,Single Family,Detached House,3,3,966.0,1.025953,South,1
17,2009-01-05,2009,Waterbury,51450.0,187900.0,Three Family,Triplex,6,5,1825.0,1.025953,North,1
18,2009-01-05,2009,Bridgeport,97719.0,265000.0,Two Family,Duplex,4,2,NaN,1.025953,North,1
19,2009-01-05,2009,Fairfield,793240.0,800000.0,Single Family,Detached House,3,1,1064.0,1.025953,South,1

In [31]:
df.loc[df.Month == 8].count()

Date                 1050
Year                 1050
Locality              925
Estimated Value       920
Sale Price           1050
Property             1050
Residential          1050
num_rooms            1050
num_bathrooms        1050
carpet_area           915
property_tax_rate    1050
Face                 1050
Month                1050
dtype: int64

In [37]:
df_new = df.groupby('Locality')['Sale Price'].mean()
print(df_new.idxmax(),
df_new.max())

Greenwich 2270223.539495238